### ISSUE TITLE
These seven city names are converted to Romaji incorrectly

### ISSUE THREAD

**Issue by rperkner** [hexenq/kuroshiro.js#18] opened 2017-10-12 06:18 UTC
Japanese city names listed below are converted to Romaji incorrectly:

宇城市
西予市
筑西市
東筑摩郡筑北村
南会津郡檜枝岐村
邑智郡邑南町
諫早市

Observed are (incorrect), listed in the same order as above:

宇 joushi
nishi 予 shi
筑 saichi
higashichikuma gun 筑 kitamura
minamiaidu gun hinoki eda 岐 mura
ouchi gun 邑 minamimachi
諫 sou shi

Expected are (correct), listed in the same order as above:

uki shi
seiyo shi
chikusei shi
higashi chikuman gun chikuhoku mura
minami aizu gun hinoemata mura
ochi gun onan cho
isahaya shi

**Comment by hexenq** [comment] 2017-11-21 03:41
Duplicate of #11 . Thanks for your feedback. At present, it's up to you to choose the adequate dictionary to meet your tokenization requirements.

**Closed by hexenq** 2017-11-21 03:41 UTC
Labels: duplicate
