### ISSUE TITLE
Can 字 be pronounced as “aza” instead of “ji”?

### ISSUE THREAD

**Issue by pckoay** [hexenq/kuroshiro.js#16] opened 2017-08-21 11:17 UTC
Hi,

I would like to check, when 字 is used in address, can it be pronounced as “aza” instead of “ji” ?

**Comment by saphryn** [comment] 2017-10-12 04:38
It can, but usually only when paired, i.e. 小字(こあざ) and 大字(ōaza).

**Comment by pckoay** [comment] 2017-10-12 05:40
Hi Saphryn,

Thanks for the reply. I tried to transliterate 小字 and 大字 just now,  小字 will return "KOAZA" while 大字 will return "DAIJI". It looks like it will not return "aza" in 大字.

Do you know the reason?

**Comment by hexenq** [comment] 2017-11-21 03:40
Duplicate of #11 . Thanks for your feedbacks. At present, it's up to you to choose the adequate dictionary to meet your tokenization and pronunciation requirements.

**Closed by hexenq** 2017-11-21 03:40 UTC
Labels: duplicate
