### ISSUE TITLE
[牛丼]という漢字

### ISSUE THREAD

**Issue by nemeros111** [hexenq/kuroshiro.js#20] opened 2017-12-28 08:28 UTC
「牛丼]　→　うしどんぶり
になっちゃいます。

**Comment by hexenq** [comment] 2018-01-22 08:12
Duplicate of #11 . Thanks for your feedbacks. At present, it's up to you to choose the adequate dictionary to meet your tokenization and pronunciation requirements.

**Closed by hexenq** 2018-01-22 08:12 UTC
Labels: duplicate
