### ISSUE TITLE
Kanji Characters Not Transliterated 

### ISSUE THREAD

**Issue by pckoay** [hexenq/kuroshiro.js#14] opened 2017-07-10 10:32 UTC
Hi,

Is there any reason why some of following Kanji Characters could not be transliterated when the demo is used? 
Example: 赦 哀 肯

**Comment by hexenq** [comment] 2017-11-21 03:12
Duplicate of #11 . Thanks for your feedback. At present, it's up to users to choose the adequate dictionary to meet their tokenization requirements.

**Closed by hexenq** 2017-11-21 03:12 UTC
